### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Miliardi** [stackblitz-labs/bolt.diy#1106]
### Describe the bug

Bolt.new works but Bolt.diy not

pnpm run dev

> bolt@0.0.5 dev /Users/la/Documents/Dev/BOLT/bolt.diy
> node pre-start.cjs  && remix vite:dev

★═══════════════════════════════════════★
          B O L T . D I Y
         ⚡️  Welcome  ⚡️
★═══════════════════════════════════════★

📍 Current Version Tag: v"0.0.5"
📍 Current Commit Version: "41bb909"
  Please wait until the URL appears here
★═══════════════════════════════════════★
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
dyld: malformed mach-o image: dyld chained fixups info underruns __LINKEDIT
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:87:19)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

https://github.com/stackblitz-labs/bolt.diy

### Steps to reproduce

pnpm install
pnpm run dev

### Expected behavior

Starting the Bolt DIY

### Platform

Mac OS

**Comment by leex279** [comment]
Hi @Miliardi,

we a similar case these days in the community and for the guy PNPM not worked but NPM. 

Can you please test with npm on a fresh git clone please.

```
npm install
npm run dev

```

**Comment by Miliardi** [comment]
> Hi [@Miliardi](https://github.com/Miliardi),
> 
> we a similar case these days in the community and for the guy PNPM not worked but NPM.
> 
> Can you please test with npm on a fresh git clone please.
> 
> ```
> npm install
> npm run dev
> ```

Unfortunately does not work as well. Hae been fighting with t for several hours already.

Interesting that Bolt.new starts with pnpm without any issues

**Comment by Miliardi** [comment]
> Hi [@Miliardi](https://github.com/Miliardi),
> 
> we a similar case these days in the community and for the guy PNPM not worked but NPM.
> 
> Can you please test with npm on a fresh git clone please.
> 
> ```
> npm install
> npm run dev
> ```

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:159:15)
    at writeGeneric (node:internal/stream_base_commons:150:3)
    at Socket._writeGeneric (node:net:964:11)
    at Socket._write (node:net:976:8)
    at writeOrBuffer (node:internal/streams/writable:572:12)
    at _write (node:internal/streams/writable:501:10)
    at Socket.Writable.write (node:internal/streams/writable:510:10)
    at Runtime.updateConfig (/BOLT/bolt.diy-0.0.5/node_modules/miniflare/src/runtime/index.ts:154:24)
    at Miniflare2.#assembleAndUpdateConfig (/BOLT/bolt.diy-0.0.5/node_modules/miniflare/src/index.ts:1397:28)
    at Mutex.runWith (/BOLT/bolt.diy-0.0.5/node_modules/miniflare/src/workers/shared/sync.ts:66:45)
    at Miniflare2.#waitForReady (/BOLT/bolt.diy-0.0.5/node_modules/miniflare/src/index.ts:1485:3)
    at Miniflare2._getProxyClient (/BOLT/bolt.diy-0.0.5/node_modules/miniflare/src/index.ts:1691:3)
    at Miniflare2.getBindings (/BOLT/bolt.diy-0.0.5/node_modules/miniflare/src/index.ts:1714:23)
    at getPlatformProxy (/BOLT/bolt.diy-0.0.5/node_modules/wrangler/wrangler-dist/cli.js:128209:20)
    at configureServer (/BOLT/bolt.diy-0.0.5/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///BOLT/bolt.diy-0.0.5/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (/BOLT/bolt.diy-0.0.5/node_modules/@remix-run/dev/dist/vite/plugin.js:768:27)
    at async Promise.all (index 3)
    at resolveConfig (file:///BOLT/bolt.diy-0.0.5/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66404:3)
    at _createServer (file:///BOLT/bolt.diy-0.0.5/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:62758:18)
    at dev (/BOLT/bolt.diy-0.0.5/node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
    at Object.viteDev (/BOLT/bolt.diy-0.0.5/node_modules/@remix-run/dev/dist/cli/commands.js:221:3)
    at Object.run (/BOLT/bolt.diy-0.0.5/node_modules/@remix-run/dev/dist/cli/run.js:271:7) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by Miliardi** [comment]
npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@blitz/eslint-plugin@0.1.0',
npm warn EBADENGINE   required: { node: '^18.0.0 || ^20.0.0' },
npm warn EBADENGINE   current: { node: 'v22.12.0', npm: '10.9.0' }
npm warn EBADENGINE }
npm warn deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

**Comment by leex279** [comment]
**Take a look at these topics. Maybe you find something that helps:**
- https://thinktank.ottomator.ai/t/how-to-install-bolt-diy-on-mac/4105/27
- https://thinktank.ottomator.ai/t/running-bolt-diy-on-macos/4203
- https://thinktank.ottomator.ai/t/i-could-use-some-help-installing/4344/45

**Comment by Miliardi** [comment]
Whatever I try I get

dyld: malformed mach-o image: dyld chained fixups info underruns __LINKEDIT
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:87:19)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.

Bolt.new locally starts fine at the same time

**Comment by tranghaviet** [comment]
I confirmed this issue still happen on my machine.
Node v20.17.0 / v22.13.1
pnpm v9.9.0

**Comment by tranghaviet** [comment]
My solution: checkout to commit `3be18e3`

**Comment by Miliardi** [comment]
An unethical developer who, using underhanded methods, seeks out those who created a ticket here in other networks and tries to publicly shame them instead of addressing the issue or simply admitting that they cannot resolve it.

**Comment by leex279** [comment]
Hi @Miliardi,
I sorry you feel like that, but for me still nothing bad on this. Youtube, as well as the community are public in the internet and there is nothing "underhandeded methods" for linking a the community post in a youtube comment, so other how got the same problem, can get involved and find solutions as well.
There is also no shaming at all in my view, cause if this ashames you, you would need to be ashamed by posten your problem here as well.

As I see you now also deleted the comment in youtube, so no one else can verify what you are writing here ;). 

---------------------

If you want to discuss further, please write me a private message in the community, so we can clarify there.

**Comment by coleam00** [comment]
> > Hi [@Miliardi](https://github.com/Miliardi), I sorry you feel like that, but for me still nothing bad on this. Youtube, as well as the community are public in the internet and there is nothing "underhanded methods" for linking a community post in a youtube comment, so others who got the same problem, can get involved and find solutions as well. There is also no shaming at all in my view, cause if this ashames you, you would need to be ashamed by posting your problem here as well.
> > As I see you now also deleted the comment in youtube, so no one else can verify what you are writing here ;).
> 
> I see that you don't see anything wrong with you sharing personal data about your users who created a case on GitHub on public platforms like YouTube. And you consider this absolutely ethical, worthy, and professional behavior.
> 
> I think further discussion with such a person is pointless.

@Miliardi, leex279 has done nothing but help the bolt.diy community. He's constantly involved in assisting with issues like this, making guides for all of us in our community and on YouTube, helping us plan new features, and testing PRs. There is nothing wrong with what he's done here from what I can tell and I certainly don't want to discourage him from trying to keep things organized and help work through issues which is all I've seen him do here.

There is no personal data being shared here when everything is public.

**Comment by Miliardi** [comment]
@coleam00 

> There is nothing wrong with what he's done here

You obviously didn’t see yourself what he has done on YouTube.

> I certainly don't want to discourage him from trying to keep things organized and help work through issues

I understand that it is your main motivation and that you don’t care about private data he reveals as long as he helps you here.

> There is no personal data being shared here

Maybe not here but he linked my several personal accounts together in his public message on social media with this very case on GitHub without any reason for this, which certainly cannot be considered ethical and professional behavior, and I am encountering this for the first time.

**Comment by Datata1** [comment]
for me checking out on commit ```3be18e3``` did not helped. Does anyone knows why this happens?

**Comment by Datata1** [comment]
Alright thank you. I am working on an Ubuntu 20.04.6 and unfortunately i cant change the OS since i am working in a cloud environment. 

I tried to change the node version, i switched from pnpm to npm, updated some dependencies and i run now with npx. after changing some vite configurations i get now this error:

```
TypeError: renderToReadableStream is not a function
    at handleRequest (/home/user/app/app/entry.server.tsx:19:26)
    at handleDocumentRequest (/home/user/app/node_modules/@remix-run/server-runtime/dist/server.js:400:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at requestHandler (/home/user/app/node_modules/@remix-run/server-runtime/dist/server.js:170:18)
    at nodeHandler (/home/user/app/node_modules/@remix-run/dev/dist/vite/plugin.js:868:27)
    at /home/user/app/node_modules/@remix-run/dev/dist/vite/plugin.js:871:15
```

**Comment by Miliardi** [comment]
Unfortunately changing node version or to npx didn’t help me either

**Comment by yepaoxixi** [comment]
我这边测试是wrangler版本导致的，linux系统版本不同导致安装的wrangler版本有差异，pnpm list |grep wrangler看一下他的版本。我这里把他的版本改为“wrangler": "3.104.0"正常了  -- 这也是部分bolt.new ok bolt.diy 不ok的原因，恰好在同环境安装了不同版本的wrangler！

如果不行一个个小版本切换试试大概率可以的，good luck！
